### ISSUE TITLE
Evaluate Kubernetes, ECS, Docker Swarm... to decide which will be our docker cluster solution

### ISSUE THREAD

**Issue by jorge-klikin** [klikin-labs/docker-files#10]

**Comment by balder-klikin** [comment]
Kubernetes documentation is kinda poor at this moment. I was able to run a cluster on AWS, but couldn't manage to deploy any containers on it.

**Comment by balder-klikin** [comment]
### Amazon ECS
- really easy to set up and use

**Comment by balder-klikin** [comment]
### Amazon ECS
- [-] not yet suitable for production
- [+] easy to set up and use
- [+] mantained by Docker
